dist: bionic

language: node_js
node_js:
  - "12.5"

script:
  - commitlint-travis
  - where commitlint-travis || which commitlint-travis
  - npm run build
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: never
