name: 'Self-Hosted Renovate'
description: 'GitHub Action to run self-hosted Renovate.'
author: 'Jeroen de Bruijn'
inputs:
  configurationFile:
    description: 'Renovate configuration file'
    required: false
    default: 'src/config.js'
  token:
    description: |
      Personal access token that Renovate should use. This should be stored as
      secret.
    required: true
runs:
  using: 'docker'
  image: 'src/Dockerfile'
  args:
    - ${{ inputs.configurationFile }}
    - ${{ inputs.token }}
