language: none
env:
  matrix:
    - FORMULA: cmake@3.1.0.rb
    - FORMULA: cmake@3.1.1.rb
    - FORMULA: cmake@3.1.2.rb
    - FORMULA: cmake@3.1.s.rb
build:
  ci:
    - 'echo "building formula ./Formula/${FORMULA}"'
    - shipctl copy_file_from_prev_state "hashes.json" .
    - cat hashes.json
    - echo "building formula ./Formula/${FORMULA}" >> "hashes.json"
    - cat hashes.json
    - shipctl copy_file_to_state "hashes.json"
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - '--last_committer'
        - '--last_author'
      sendConsoleLogs: true
      on_success: never
      on_failure: never
      on_cancel: never
      on_start: never
      on_pull_request: never

resources:
  - name: someParams
    type: params
    version:
      params:
        KEY1: "sdf"
        

jobs:
  - name: deployChanges
    type: runSh
    dependencyMode: strict
    steps:
      - IN: ci-fiddle_runCI
      - TASK:
        - script: |
          echo "deploying now"
          shipctl copy_file_from_prev_state "hashes.json" .
          echo "done"
          cat "hashes.json"
