language: none
env:
  matrix:
    - FORMULA: cmake@3.1.0.rb
    - FORMULA: cmake@3.1.1.rb
    - FORMULA: cmake@3.1.2.rb
    - FORMULA: cmake@3.1.s.rb
build:
  ci:
    - 'echo "building formula ./Formula/${FORMULA}"'
    - echo "building formula ./Formula/${FORMULA}" >> test.txt
    - shipctl post_resource_state res_state "HERO" "Superman ${FORMULA}"
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - '--last_committer'
        - '--last_author'
      sendConsoleLogs: true
      on_success: never
      on_failure: never
      on_cancel: never
      on_start: never
      on_pull_request: never

resources:
  - name: res_state
    type: state
    version:
        
jobs:
  - name: ci-fiddle_runCI
    type: runCI
    steps:
      - IN: ci-fiddle_ciRepo
      - OUT: res_state
  - name: deployChanges
    type: runSh
    dependencyMode: strict
    steps:
      - IN: ci-fiddle_runCI
      - IN: res_state
      - TASK:
        - script: echo "deploying now"
        - script: shipctl get_resource_version_key res_state "HERO"

