language: none
env:
  matrix:
    - FORMULA: cmake@3.1.0.rb
    - FORMULA: cmake@3.1.1.rb
    - FORMULA: cmake@3.1.2.rb
    - FORMULA: cmake@3.1.s.rb
build:
  ci:
    - 'echo "building formula ./Formula/${FORMULA}"'
    - echo "building formula ./Formula/${FORMULA}" >> test.txt
    - shipctl put_resource_state_multi "myParams" "username=admin password=${FORMULA}"
integrations:
  notifications:
    - integrationName: email
      type: email
      recipients:
        - '--last_committer'
        - '--last_author'
      sendConsoleLogs: true
      on_success: never
      on_failure: never
      on_cancel: never
      on_start: never
      on_pull_request: never

resources:
  - name: myParams
    type: params
    versionTemplate:
      params:
        username: tbd
        password: tbd
        
        
jobs:
  - name: ci-fiddle_runCI
    type: runCI
    steps:
      - IN: ci-fiddle_ciRepo
      - OUT: myParams
  - name: deployChanges
    type: runSh
    dependencyMode: strict
    steps:
      - IN: ci-fiddle_runCI
      - IN: myParams
      - TASK:
        - script: 
          - echo "deploying now"
          - echo $username
          - echo $password

