#!/bin/bash -e
export CMAKE_VERSION='3.1.0'

echo "================================ Clean apt-get ================================="
apt-get clean
mv /var/lib/apt/lists /tmp
mkdir -p /var/lib/apt/lists/partial
apt-get clean
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update
echo "=============================== Cleaned apt-get ================================"

echo "========== Installing CMake ===================================================="
. /uxx-cmake/cmake/install
echo "========== Successfully installed CMake ========================================"
