#!/bin/bash -e
#
# Build docker image.

################################################################################
# Configuration
################################################################################
# Fail on first error
set -e

################################################################################
# Constants
################################################################################


################################################################################
# Global variables
################################################################################


################################################################################
# Functions
################################################################################
########################################
# Build Docker image.
#
# Globals:
#   None
# Arguments:
#   cmake_version CMake version to be installed.
#   ubuntu_version Ubuntu version to use the DockerFile of.
#   image_name Name of the image.
#   image_tag Tag of the image.
# Returns:
#   None
########################################
docker::build() {
  local cmake_version="${1}"
  local ubuntu_version="${2}"
  local image_name="${3}"
  local image_tag="${4}"
  
  docker build --build-arg CMAKE_VERSION="${cmake_version}" \
               --file "./ubuntu_${ubuntu_version}.DockerFile" \
               --tag "${image_name}:${image_tag}" \
               .
}

main() {
  docker::build "${@}"
}

main "${@}"
