#!/bin/bash -e
#
# Build docker image.

################################################################################
# Configuration
################################################################################
# Fail on first error
set -e

################################################################################
# Constants
################################################################################


################################################################################
# Global variables
################################################################################


################################################################################
# Functions
################################################################################
########################################
# Build Docker image.
#
# Globals:
#   None
# Arguments:
#   docker_file Name of the dockerfile without extension.
#   image_name Name of the image.
#   image_tag Tag of the image.
# Returns:
#   None
########################################
docker::build() {
  local docker_file="${1}"
  local image_name="${2}"
  local image_tag="${3}"

  docker build --file "./${docker_file}.DockerFile" \
               --tag "${image_name}:${image_tag}" \
               .
}

# Yeahh, this will teach them

main() {
  docker::build "${@}"

  # here here
}

main "${@}"
