#!/bin/bash -e
#
# Build docker image.

################################################################################
# Configuration
################################################################################
# Fail on first error
set -e

################################################################################
# Constants
################################################################################


################################################################################
# Global variables
################################################################################


################################################################################
# Functions
################################################################################
########################################
# Build Docker image.
#
# Globals:
#   None
# Arguments:
#   cmake_version CMake version to be installed.
#   linux_version Linux version (e.g. ubuntu_1404) to use the DockerFile of.
#   image_name Name of the image.
#   image_tag Tag of the image.
# Returns:
#   None
########################################
docker::build() {
  local linux_version="${1}"
  local image_name="${2}"
  local image_tag="${3}"

  docker build --file "./${linux_version}.DockerFile" \
               --tag "${image_name}:${image_tag}" \
               .
}

main() {
  docker::build "${@}"
}

main "${@}"
