#!/bin/bash

set -e

# Get the current working directory, i.e. the directory of this file. All
# credits for this line goes to this guy https://stackoverflow.com/a/246128.
readonly WORKING_DIRECTORY="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd
)"

# Source the versions file to 'include' the CMake version list.
source "${WORKING_DIRECTORY}/versions"

readonly BASE_URL='https://github.com/Kitware/CMake/releases/download'
readonly CMAKE_BASE_PATH='/usr/local/cmake'
mkdir "${CMAKE_BASE_PATH}"

for cmake_version in "${CMAKE_VERSIONS[@]}"; do
  printf "Installing CMake ${cmake_version}... "

  filename="cmake-${cmake_version}-Linux-x86_64"
  archive_filename="${filename}.tar.gz"
  url="${BASE_URL}/v${cmake_version}/${archive_filename}"

  wget -q "${url}"


  tar -xz --file "${archive_filename}"

  mkdir "/usr/local/cmake/${cmake_version}"
  cp -r "./${filename}"/* "/usr/local/cmake/${cmake_version}/"
  ln -s "/usr/local/cmake/${cmake_version}/bin/cmake" "/usr/local/bin/cmake-${cmake_version}"

  installed_cmake_version=$(
    "/usr/local/cmake/${cmake_version}/bin/cmake" --version | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+'
  )

  if [[ "${installed_cmake_version}" != "${cmake_version}" ]]; then
    echo "Installed CMake (${installed_cmake_version}) doesn't match expected" \
         "version (${cmake_version})"
    exit 1
  fi

  rm -r "${filename}"
  rm "${archive_filename}"
  echo "OK"
done


echo "export CMAKE_BASE_PATH='${CMAKE_BASE_PATH}'" >> ~/.bashrc
echo "source /linux-cmake/cmake/versions" >> ~/.bashrc

echo "${CMAKE_BASE_PATH}/${CMAKE_VERSIONS[0]}/"
ls -la "${CMAKE_BASE_PATH}/${CMAKE_VERSIONS[0]}/bin/"
ls -la "${CMAKE_BASE_PATH}/${CMAKE_VERSIONS[0]}/"


ls -la /usr/local/bin
ln -s "${CMAKE_BASE_PATH}/${CMAKE_VERSIONS[0]}/bin/"* /usr/local/bin

ls -la /usr/local/bin

