#!/bin/bash

set -e
# Install GNU ARM Embedded Toolchain, including dependencies, and add it to the path.
#
# Name                          | Location
# ----------------------------- | ----------
# lib32bz1                      | default
# lib32ncurses5                 | default
# lib32bz2-1.0                  | default
# libarchive-zip-perl           | default
# gcc-arm-none-eabi-4_9-2015q3  | /usr/local
# ------------------------------------------
#
# Author   : Jeroen de Bruijn
# Date     : 16 February 2017, 22:02
# Version  : 1.3
#
# Changelog
# Changes since v1.2
#   - Remove unnecessary sudo.
#   - Use -nv instead of --no-verbose because it looks cleaner.
#   - Don't append PATH since it is now set in the Dockerfile. Otherwise would be getting double entries.
# Changes since v1.1
#   - Just append PATH to .bashrc. The path is now also set in the Dockerfile.
# Changes since v1.0
#   - Append PATH to both .bashrc and .profile
echo "Version: ${CMAKE_VERSION}"
readonly VERSION=${CMAKE_VERSION}
readonly FILENAME="cmake-${VERSION}-Linux-x86_64"
readonly ARCHIVE_FILENAME="${FILENAME}.tar.gz"
readonly URL="https://github.com/Kitware/CMake/releases/download/v${VERSION}/${ARCHIVE_FILENAME}"


wget -nv "${URL}"
tar xzf "./${ARCHIVE_FILENAME}"
ls -la "./${FILENAME}"

cp -R "./${FILENAME}" /usr/local/
rm -r "./${ARCHIVE_FILENAME}" "./${FILENAME}"

/usr/local/${FILENAME}/bin/cmake --version
