name: Commitlint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: wagoid/commitlint-github-action@v1.2.2
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint source code
        run: |
          date
          npm ci
          npm run lint
          exit 10
  build:
    needs: [lint, lint-js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          date
          npm ci
          npm run build
