name: Commitlint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: wagoid/commitlint-github-action@v1.2.2
  lint-js:
    container: vidavidorra/docker-linux:ubuntu1804-master
    steps:
      - uses: actions/checkout@v1
      - name: Install & build
        run: |
          npm ci
          npm run build
      - name: Check versions
        run: |
          brew --version
          gcc --version
          which gcc
