name: Commitlint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: wagoid/commitlint-github-action@v1.2.2
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
          npm ci
      - name: Check build is needed
        run: npm run testjs
        id: build_needed
      - name: Build thing
        if: steps.build_needed.outputs.needs_build
        run: |
          echo "Yay, we're building this shit!"
          npm run build
  build:
    needs: [lint, lint-js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          date
          npm ci
          npm run build
