name: Commitlint
on: [push]

jobs:
  lint:
    runs-on: ubuntu-16.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - uses: wagoid/commitlint-github-action@v1.2.2
