name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.commits[0].message, 'chore(release): trigger release process [ci release]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install project
        run: npm ci
      - name: Setup Git user
        run: |
          git config --local user.name "GitHub"
          git config --local user.email "noreply@github.com"
      - name: Release as major
        if: endsWith(github.event.commits[0].message, '[ci release][major]')
        run: npx --no-install standard-version --release-as major
      - name: Release as minor
        if: endsWith(github.event.commits[0].message, '[ci release][minor]')
        run: npx --no-install standard-version --release-as minor
      - name: Release as patch
        if: endsWith(github.event.commits[0].message, '[ci release][patch]')
        run: npx --no-install standard-version --release-as patch
      - name: Release
        if: endsWith(github.event.commits[0].message, '[ci release]')
        run: |
          git status
          git branch
          npx --no-install standard-version
          git status
          git log
          git tag --list
        shell: bash
      - name: Fix commit author
        run: |
          git tag --list
          git commit --amend --no-edit --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Build artifacts
        run: |
          echo 'Build whatever artifacts the project has'
          git tag --list
          git status
          git log
      - name: Push release
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
      - name: Publish
        run: echo 'Publish this version!'
  prevent_failed_status:
    name: Prevent failed status when skipped
    runs-on: ubuntu-latest
    steps:
      - name: Prevent failed status when skipped
        run: |
          echo "Run this job to prevent the workflow status from showing as failed when all other jobs are skipped."
