name: Renovate
on:
  push:
    branches:
      - master
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: '0/10 * * * *'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: echo 'do stuff...'
