name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install project
        env:
          GPR_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
        run: |
          echo '//npm.pkg.github.com/:_authToken=${GPR_AUTH_TOKEN}' >> ~/.npmrc
          ls -la ~/
          echo $HOME
          cat ~/.npmrc || echo fail
          npm ci
      - name: Lint
        run: npm run lint
