name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install project
        env:
          GPR_AUTH_TOKEN: ${{ secrets.GPR_READ_TOKEN }}
          NPM_CONFIG_FILE: ~/.npmrc
        run: |
          echo 'start'
          touch $NPM_CONFIG_FILE
          echo 'start2'
          touch ~/.npmrc
          echo 'start3'
          echo '//npm.pkg.github.com/:_authToken=${GPR_AUTH_TOKEN}' > ${NPM_CONFIG_FILE}
          echo 'created config'
          npm ci
          echo 'remove'
          rm ${NPM_CONFIG_FILE}
      - name: Lint
        run: npm run lint
