name: Renovate
on:
  push:
    branches:
      - master
jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: vidavidorra/docker-linux:ubuntu1804-master
      options: -v ./src:/volume_mount
    steps:
      - name: Upload
        run: |
          echo 'hello'
          pwd
          ls -la
          ls -la /volume_mount
